// Minimal Database type stub so supabase-js can type the RPC + table calls.
// Generated by hand to mirror supabase/migrations/0001_initial_schema.sql.
// Keep in sync if the schema changes.

export type Database = {
  kalshi: {
    Tables: {
      markets: {
        Row: {
          ticker: string;
          event_ticker: string | null;
          title: string | null;
          close_time: string | null;
          expected_expiry: string | null;
          last_seen_at: string;
          last_ask_cents: number | null;
          last_bid_cents: number | null;
          last_volume: number | null;
          last_open_interest: number | null;
          resolved: boolean;
          outcome: "yes" | "no" | null;
        };
        Insert: never;
        Update: never;
      };
      sim_orders: {
        Row: {
          id: number;
          ticker: string;
          side: string;
          action: string;
          bid_cents: number;
          quantity: number;
          placed_at: string;
          status: "open" | "filled" | "cancelled";
          fill_price_cents: number | null;
          filled_at: string | null;
          cancelled_at: string | null;
          cancel_reason: string | null;
          pnl_cents: number | null;
          resolved_at: string | null;
          notes: string | null;
          updated_at: string;
        };
        Insert: never;
        Update: never;
      };
      events: {
        Row: {
          id: number;
          ts: string;
          kind: string;
          ticker: string | null;
          order_id: number | null;
          payload: Record<string, unknown>;
        };
        Insert: never;
        Update: never;
      };
    };
    Views: {
      daily_pnl: {
        Row: {
          day: string;
          pnl_cents: number;
          orders_resolved: number;
          wins: number;
          losses: number;
        };
      };
      open_positions: {
        Row: {
          id: number;
          ticker: string;
          title: string | null;
          close_time: string | null;
          fill_price_cents: number;
          quantity: number;
          current_ask_cents: number | null;
          filled_at: string;
          unrealized_pnl_cents: number | null;
        };
      };
    };
    Functions: {
      account_summary: {
        Args: { bankroll_cents: number };
        Returns: {
          bankroll_cents: number;
          realized_pnl_cents: number;
          unrealized_pnl_cents: number;
          account_value_cents: number;
          open_position_count: number;
          open_position_cost_cents: number;
          total_fills: number;
          total_resolved: number;
          wins: number;
          losses: number;
          win_rate: number | null;
        }[];
      };
      recent_events: {
        Args: { limit_n?: number; since_hours?: number };
        Returns: {
          id: number;
          ts: string;
          kind: string;
          ticker: string | null;
          order_id: number | null;
          payload: Record<string, unknown>;
        }[];
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
